### ISSUE TITLE
修改齿包称呼

### ISSUE THREAD

**Issue by yqs112358** [LiteLDev/LipUI#15]
<img width="284" alt="image" src="https://user-images.githubusercontent.com/37969157/228319133-45f218a4-23a8-4576-9c1b-0dfeb3a98b5c.png">

“齿包”对新人来说含义不明，而且没有用于解释的UI或者说明。建议修改为LipUI - LL插件包管理器 或者 tooth包管理器（？有待讨论）
关联 #11

**Comment by LazuliKao** [comment]
tooth包吧，好像lip文档都是这么写的

**Comment by yqs112358** [comment]
可以，做好说明就行。可以整个什么新手指引之类
