### ISSUE TITLE
改进设置页面UI设计

### ISSUE THREAD

**Issue by yqs112358** [LiteLDev/LipUI#16]
<img width="538" alt="image" src="https://user-images.githubusercontent.com/37969157/228320425-b0319127-6abc-478a-8100-2be8b3d5874e.png">

略有些大小不一，可以进行一些网格化的改动。关于 那边挺好看，上面的设置略有凌乱
可以改成设置选项左对齐，设置控件右对齐，或者一行两个设置（？具体设计优化有待讨论）

**Comment by LazuliKao** [comment]
![image](https://user-images.githubusercontent.com/46601807/229270579-dc4bf2b4-c66e-4413-bbde-a1df8cba4273.png)

**Comment by yqs112358** [comment]
😍😍
