### ISSUE TITLE
部分情况下 lipUI无法正常处理Lip的confirmation

### ISSUE THREAD

**Issue by harry-xi** [LiteLDev/LipUI#3]
表现见 #2 
当bds作为依赖安装时（如安装ll作为依赖安装bds是）该功能是正常的，独立安装bds就会发生#2所述情况

**Comment by LazuliKao** [comment]
已修改，请测试actions构建

**Comment by harry-xi** [comment]
> 已修改，请测试actions构建

已解决，但是不得不说，我觉得旧方案一起确认lip的所有confirmation似乎更优雅（或者实际上那玩意干脆不是依据Lip的输出/Lip的tooth文件判断的？我没注意过相关源码)
