### ISSUE TITLE
无法正确定位lip.exe的位置

### ISSUE THREAD

**Issue by laoyali** [LiteLDev/LipUI#4]
**问题描述**

如题

在已经安装lip的条件下（系统环境变量已添加）

![image](https://user-images.githubusercontent.com/58849532/219874456-c787272c-90a8-4060-85c5-2669e8a22966.png)

若用户首次打开lip-ui

无法自动定位lip.exe的位置

![image](https://user-images.githubusercontent.com/58849532/219874503-74c1f656-a5b3-48fc-8994-37b6664c7a61.png)

**环境**
OS：WIN10 22H2
lip：已安装并添加至系统变量

**Comment by LazuliKao** [comment]
未能复现
