### ISSUE TITLE
部分UI设计改进建议

### ISSUE THREAD

**Issue by yqs112358** [LiteLDev/LipUI#5]
# 未找到Lip页面
<img width="292" alt="image" src="https://user-images.githubusercontent.com/37969157/219874732-4a4b12fa-5455-48f4-9ceb-c92eae6a0a0e.png">
随便提供一种布局思路：
<img width="312" alt="image" src="https://user-images.githubusercontent.com/37969157/219874715-64cafb9d-f46b-449e-a0cd-ef93a2a22b6d.png">

事实上手动配置可以缩小为底部的一个小链接，尽量引导为自动安装

或者直接做一个对话框，“未找到Lip，是否选择自动安装？”
下面三个按钮：自动安装 手动配置 退出

自动安装的话最好还是下载完安装包想办法让他自动安装，目前下完之后还要点几下下一步啥的，还要选安装路径，这个就跟Lip那边形成了重复，逻辑让人感觉比较奇怪。

# 工作路径页面
<img width="314" alt="image" src="https://user-images.githubusercontent.com/37969157/219874765-42ed72d7-8118-4a60-a488-10c8fa929dcc.png">
页面紧凑一点，另外建议改成选完点确认直接完毕，而不是先点添加再确认（一开始我也迷惑了一会）
工作路径最好默认填上，比如桌面的Lip目录 / BDS目录，然后如果目录不存在的话自动创建

> 补一下我个人意见，毕竟Lip是主要为了LL服务的，然后GUI又是为了方便小白，所以建议直接第一次启动的时候弹窗询问是否需要先安装BDS，然后直接把BDS LL啥的都装好

# 预览页面
<img width="297" alt="image" src="https://user-images.githubusercontent.com/37969157/219875015-469dc69e-181d-465c-9bd1-fb08553ea923.png">
预览页面半透明寄了，建议改成窗口不透明，窗口外面半透明。
另外这个窗口感觉像是绝对定位的？有无什么办法直接撑开在中间，看起来自然一点。

# 安装中
<img width="304" alt="image" src="https://user-images.githubusercontent.com/37969157/219875082-e112064a-abee-41f7-93b2-ba1d15b48a55.png">
这里的提示语略有迷惑，可以把整个按钮文字改成 停止，然后如果停止会发生问题的话，弹窗确认

# 安装完
安装完毕之后应该让页面呈现出和安装前不一样的效果
比如这里的安装按钮变成卸载，然后随便哪里加点绿色啥的，让人能感觉跟没装之前是不一样的状态
这里的取消 获取可以去掉，改成在这个输入框停止输入2-3s后（或者失去焦点后）自动拉取，将状态用一个小图标显示在地址栏右侧。如果成功拉取到直接加载那些安装信息
<img width="609" alt="image" src="https://user-images.githubusercontent.com/37969157/219875251-d690a1ed-fa17-4ee1-aa1d-abbd7389f34d.png">

**Comment by LazuliKao** [comment]
这个issue怎么这么长（

**Comment by yqs112358** [comment]
我考完试来改一下（

**Comment by Futrime** [comment]
如果要弄启动时弹窗推荐安装，那么请安装starterpack，而不是ll，因为这个包含了部分最核心的基础插件，例如llmoney

**Comment by lgc2333** [comment]
安装中的那个圈圈进度 应该是从圆圈顶部开始顺时针转的 现在这样看起来很奇怪
![image](https://user-images.githubusercontent.com/59048777/219951348-4202c756-7cc7-4d6e-b559-6fb80b0aaee9.png)

**Comment by LazuliKao** [comment]
> 安装中的那个圈圈进度 应该是从圆圈顶部开始顺时针转的 现在这样看起来很奇怪 ![image](https://user-images.githubusercontent.com/59048777/219951348-4202c756-7cc7-4d6e-b559-6fb80b0aaee9.png)

这个在最新构建改好了，从顶部转下来

**Comment by lgc2333** [comment]
> > 安装中的那个圈圈进度 应该是从圆圈顶部开始顺时针转的 现在这样看起来很奇怪 ![image](https://user-images.githubusercontent.com/59048777/219951348-4202c756-7cc7-4d6e-b559-6fb80b0aaee9.png)
> 
> 这个在最新构建改好了，从顶部转下来

貌似方向错了，应该是顺时针转

**Comment by LazuliKao** [comment]
看起来这个issue基本好了，就close了
