### ISSUE TITLE
Releases v0.2.4 preview 存在崩溃问题。

### ISSUE THREAD

**Issue by chuxiaaaa** [LiteLDev/LipUI#9]
![QQ截图20230320174935](https://user-images.githubusercontent.com/62934376/226304073-e888908b-0289-4ce1-a1fd-1b2fe56954a2.png)
以下是dnspy给出的错误信息
![QQ截图20230320175034](https://user-images.githubusercontent.com/62934376/226304245-70a7bf0d-65aa-4a47-ad5e-8b4d60b16ad6.png)

跑源代码无异常，用这个Releases的文件就出问题

**Comment by LazuliKao** [comment]
当是添加条款的时候比较草率忘记创建文件夹了，最新的commit已经修了之后发更新
